export const STRINGS = {
  ALL_CUSTOMERS: 'All customers',
  ADD_NEW_CUSTOMER: 'Add new customer',
  SIGN_IN: 'Sign In',
  EMAIL: 'Email',
  ENTER_VALID_EMAIL: 'Enter a valid email',
  PASSWORD: 'Password',
  PASSWORD_NOT_EMPTY: 'Password should not be empty',
  BRAND: 'Brand',
  NAME: 'Name',
  NR_WIPES: 'Nr. of wipes',
  STOCK: 'Stock',
  DENSITY: 'Density',
  WIDTH: 'Width',
  FRAGRANCE: 'Fragrance',
  MATERIAL: 'Material',
  ALL_PRODUCTS: 'All products',
  ADD_NEW_PRODUCT: 'Add new product',
  ALL_SALES: 'All sales',
  ADD_NEW_SALE: 'Add new sale',
  CUSTOMER_SUCCESS: 'Customer added successfully',
  LOCATION: 'Location',
  PHONE_NUMBER: 'Phone number',
  RECEIVABLES: 'Receivables',
  PRODUCT: 'Product',
  PRICE: 'Price',
  ADD_CUSTOMER: 'Add customer',
  CANCEL: 'Cancel',
  PRODUCT_SUCCESS: 'Product added successfully',
  MATERIAL_TYPE: 'Type of material',
  ADD_PRODUCT: 'Add product',
  SALE_SUCCESS: 'Sale added successfully',
  CUSTOMER: 'Customer',
  ORDER: 'Order',
  UNITS: 'Units',
  INCOME: 'Income',
  TOTAL_INCOME: 'Total income',
  STATUS: 'Status',
  DELIVERED: 'Delivered',
  PENDING: 'Pending',
  DATE: 'Date',
  ADD_SALE: 'Add sale',
  DASHBOARD: 'Dashboard',
  SALES: 'Sales',
  PRODUCTS: 'Products',
  CUSTOMERS: 'Customers',
  PRODUCTION: 'Production',
  LOG_OUT: 'Log out',
  MARK_AS_DELIVERED: 'Mark as delivered',
  EDIT_CUSTOMER: 'Edit customer',
  EDIT_CUSTOMER_SUCCESS: 'Customer edited successfully',
  EDIT: 'Edit',
  DELETE: 'Delete',
  CONFIRM: 'Confirm',
  DELETE_SALE_DESCRIPTION:
    'By deleting a sale, you affect both product stocks and customer receivables. This action cannot be undone!',
  DELETE_SALE_TITLE: 'Are you sure you want to delete this sale?',
  DELETE_CUSTOMER_DESCRIPTION:
    'By deleting a customer, you you will lose all information about him. This action cannot be undone!',
  DELETE_CUSTOMER_TITLE: 'Are you sure you want to delete this customer?',
};
